from shutil import copy2 as copy
import Options
import Utils
import os, sys
import os.path as path
import platform

srcdir = "."
blddir = 'build'
VERSION = '0.0.1'

import platform
if platform.platform().find('Darwin') == -1:
  print >> sys.stderr, 'This extension must be built on OS X'
  sys.exit(1)

# OS X dylib linker fix
from TaskGen import feature, after
@feature('cshlib')
@after('apply_obj_vars', 'apply_link')
def kill_flag(self):
  fl = self.link_task.env.LINKFLAGS
  if '-bundle' in fl and '-dynamiclib' in fl:
     fl.remove('-bundle')
     self.link_task.env.LINKFLAGS = fl

def set_options(opts):
  opts.tool_options('compiler_cxx')
  opts.add_option('--debug', action='store_true', default=False,
                  help='build debug version')

def configure(conf):
  # todo: add --debug flag so we can set NDEBUG conditionally, omitting asserts.
  conf.check_tool('compiler_cxx')
  conf.check_tool('node_addon')
  conf.env.append_value('LINKFLAGS', [
    '-isysroot', '/Developer/SDKs/MacOSX10.6.sdk',
    '-mmacosx-version-min=10.6',
    '-framework', 'Foundation',
    '-framework', 'AppKit',
    '-dynamiclib'
  ])
  if Options.options.debug:
    conf.env['CXXFLAGS'] = list(conf.env['CXXFLAGS_DEBUG'])
  else:
    conf.env['CXXFLAGS'] = list(conf.env['CXXFLAGS_RELEASE'])
    conf.env.append_value('CXXFLAGS', ['-DNDEBUG'])

def lint(ctx):
  Utils.exec_command('test -f src/*.cc && '+
    'python cpplint.py --verbose=0 --filter='+
    '-legal/copyright,' +     # in the future
    '-build/header_guard,' +  # not interesting
    '-build/include,' +       # lint is run from outside src
    '-build/namespaces,' +    # we are not building a C++ API
    '-whitespace/comments,' +
    ' src/*.cc')

def build(ctx):
  ctx.add_pre_fun(lint)
  import TaskGen
  TaskGen.task_gen.mappings['.mm'] = TaskGen.task_gen.mappings['.cc']
  task = ctx.new_task_gen('cxx', 'shlib', 'node_addon')
  task.target = 'binding'
  task.source = ctx.path.ant_glob('src/*.cc')
  if len(task.source): task.source += ' '
  task.source += ctx.path.ant_glob('src/*.mm')

def test(ctx):
  status = Utils.exec_command('node test/all.js')
  if status != 0:
    raise Utils.WafError('tests failed')

def shutdown():
  # HACK to get binding.node out of build directory
  if Options.commands['clean']:
    if path.exists('kod/binding.node'): os.unlink('kod/binding.node')
  else:
    if path.exists('build/default/binding.node'):
      copy('build/default/binding.node', 'kod/binding.node')

